### ISSUE TITLE
BuildVision 3.1.0.7 failed to load after VS Update to 17.0.32526.225

### ISSUE THREAD

**Issue by latenightsurfer** [StefanKert/BuildVision#121]
After updating VS 2022 I get the following Exeption:

An exception was encountered while constructing the content of this frame.  This information is also logged in "C:\Users\xxx\AppData\Roaming\Microsoft\VisualStudio\17.0_3e18f44f\ActivityLog.xml".

Exception details:
System.Exception: Exception of type 'System.Exception' was thrown.
   at Microsoft.VisualStudio.Shell.Interop.IVsShell5.LoadPackageWithContext(Guid& packageGuid, Int32 reason, Guid& context)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.GetPackage()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()

[ActivityLog.xml.txt](https://github.com/StefanKert/BuildVision/files/8894349/ActivityLog.xml.txt)

**Comment by StefanKert** [comment]
Yep sorry guys.. this is actually related to #120 will close that and post an update there.
