### ISSUE TITLE
Cannot install in VS 2017

### ISSUE THREAD

**Issue by agross** [StefanKert/BuildVision#22]
When I install the vsix from [here](https://github.com/StefanKert/BuildVision/releases/tag/v1.5.0), the installation fails:

```
27.05.2017 18:45:30 - Microsoft VSIX Installer
27.05.2017 18:45:30 - -------------------------------------------
27.05.2017 18:45:30 - vsixinstaller.exe version:
27.05.2017 18:45:30 - 15.0.26430.4 built by: D15SVC
27.05.2017 18:45:30 - -------------------------------------------
27.05.2017 18:45:30 - Command line parameters:
27.05.2017 18:45:30 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VSIXInstaller.exe,C:\Users\agross\Downloads\BuildVision.vsix
27.05.2017 18:45:30 - -------------------------------------------
27.05.2017 18:45:30 - Microsoft VSIX Installer
27.05.2017 18:45:30 - -------------------------------------------
27.05.2017 18:45:30 - Failed to initialize settings for Isolated Shell C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\ssms.exe: Unable to find an entry point named '?' in DLL 'PkgdefMgmt.dll'.
27.05.2017 18:45:30 - Initializing Install...
27.05.2017 18:45:30 - Extension Details...
27.05.2017 18:45:30 - 	Identifier         : 837c3c3b-8382-4839-9c9a-807b758a929f
27.05.2017 18:45:30 - 	Name               : BuildVision
27.05.2017 18:45:30 - 	Author             : Aleksey Nagovitsyn
27.05.2017 18:45:30 - 	Version            : 1.5.0
27.05.2017 18:45:30 - 	Description        : Building process visualization.
27.05.2017 18:45:30 - 	Locale             : en-US
27.05.2017 18:45:30 - 	MoreInfoURL        : https://github.com/nagits/BuildVision
27.05.2017 18:45:30 - 	InstalledByMSI     : False
27.05.2017 18:45:30 - 	SupportedFrameworkVersionRange : [4.5,)
27.05.2017 18:45:30 - 
27.05.2017 18:45:30 - 	SignatureState     : Unsigned
27.05.2017 18:45:30 - 	Supported Products : 
27.05.2017 18:45:30 - 		Microsoft.VisualStudio.Community
27.05.2017 18:45:30 - 			Version : [15.0,16.0)
27.05.2017 18:45:30 - 		Microsoft.VisualStudio.Enterprise
27.05.2017 18:45:30 - 			Version : [15.0,16.0)
27.05.2017 18:45:30 - 		Microsoft.VisualStudio.Pro
27.05.2017 18:45:30 - 			Version : [15.0,16.0)
27.05.2017 18:45:30 - 
27.05.2017 18:45:30 - 	References         : 
27.05.2017 18:45:30 - 	Prerequisites      : 
27.05.2017 18:45:30 - 		-------------------------------------------------------
27.05.2017 18:45:30 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
27.05.2017 18:45:30 - 		Name         : Visual Studio core editor
27.05.2017 18:45:30 - 		Version      : [15.0,16.0)
27.05.2017 18:45:30 - 
27.05.2017 18:45:30 - Signature Details...
27.05.2017 18:45:30 - 	Extension is not signed.
27.05.2017 18:45:30 - 
27.05.2017 18:45:30 - Searching for applicable products...
27.05.2017 18:45:30 - Found installed product - Microsoft Visual Studio Enterprise 2015
27.05.2017 18:45:30 - Found installed product - Microsoft Visual Studio Professional 2015
27.05.2017 18:45:30 - Found installed product - Microsoft Visual Studio Community 2015
27.05.2017 18:45:30 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
27.05.2017 18:45:30 - Found installed product - Global Location
27.05.2017 18:45:30 - Found installed product - Visual Studio Enterprise 2017 (Default)
27.05.2017 18:45:30 - PKGDEF Information: Looking for master PkgDef file, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\master.pkgdef

27.05.2017 18:45:30 - PKGDEF Information: Creating PkgDefCacheNonVolatile
27.05.2017 18:45:30 - PKGDEF Information: Double-checking master pkgdef file
27.05.2017 18:45:30 - PKGDEF Information: PkgDefManagement initialized
27.05.2017 18:45:30 - PKGDEF Information: RootFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\

27.05.2017 18:45:30 - PKGDEF Information: ShellFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\

27.05.2017 18:45:30 - PKGDEF Information: PkgDefSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.admin.pkgdef

27.05.2017 18:45:30 - PKGDEF Information: ImageManifestSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions;C:\Users\agross\AppData\Local\Microsoft\VisualStudio\15.0_558ca6da\Extensions

27.05.2017 18:45:30 - PKGDEF Information: ApplicationExtensionsFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions

27.05.2017 18:45:30 - PKGDEF Information: "ZeroImpact" = dword:0, "MergeRegistry" = dword:3
27.05.2017 18:45:30 - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
27.05.2017 18:45:30 - PKGDEF Information: PkgDefCache flags, PKGDEF: 7001
27.05.2017 18:45:30 - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
27.05.2017 18:45:30 - PKGDEF Information: PkgDef cache is current.
27.05.2017 18:45:30 - PKGDEF Information: PkgDefManagement startup complete
27.05.2017 18:45:31 - The extension with ID '837c3c3b-8382-4839-9c9a-807b758a929f' is not installed to Visual Studio Enterprise 2017 (Default).
27.05.2017 18:45:31 - Found installed product - Visual Studio Build Tools 2017
27.05.2017 18:45:31 - System.IO.FileNotFoundException: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at VSIXInstaller.SupportedVSSKU.get_VersionWithBuildRevisionInfo()
   at VSIXInstaller.App.IsValidSKUForExtension(SupportedVSSKU supportedSKU, IExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.ShouldAddSkuToValidSkuList(SupportedVSSKU sku, IInstallableExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by agross** [comment]
Seems to be related to a named VS instance. On a machine without named instances the installer works.

**Comment by StefanKert** [comment]
It seems like this is an issue with the current release of VS 2017. [This thread](https://developercommunity.visualstudio.com/content/problem/32018/vsixinstallerexe-cant-install-extensions-when-visu.html) lists a workaround.

I guess this will be fixed in a release in the nearer future but for now you could try the solution in this thread.

**Comment by agross** [comment]
@StefanKert Thanks, I removed the named instance. It was created as named because I installed Build Tools before VS. It's not clear why I needed a named installation in the first place, but removing Build Tools made the VS 2017 install unnamed and the BuildVision installation succeeded.

**Comment by StefanKert** [comment]
Ok fine. Since this is a VS 2017 issue I am closing this issue. If there´s still a issue with this we can reopen it.
