### ISSUE TITLE
Install failed on latest version for 2019

### ISSUE THREAD

**Issue by spboyer** [StefanKert/BuildVision#92]
The install of '' was not successful for all of the selected products. 
For more information see...

![image](https://user-images.githubusercontent.com/7681382/76630931-32411280-6517-11ea-8f4c-182c68d481fa.png)

**Log**

```
System.MissingMethodException: Method not found: 'Void Microsoft.VisualStudio.Setup.Installer.VsixInstaller..ctor(System.IServiceProvider)'.
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by StefanKert** [comment]
Hi @spboyer ,

sorry for the delay. As I am currently working on 3.0.1 I wanted to ask if you are still facing this issue. Can you please add additional details on the VS Version you are using? 

Thanks :)

**Comment by StefanKert** [comment]
Closing since there was no update. If this issue is still existing please open another issue :) thanks.
